### ISSUE TITLE
[ Checklist ]: Final task Cross-check criteria

### ISSUE THREAD

**Issue by Exzorcist** [Exzorcist/graphiql-app#44]
# This task is needed to self-check our work. 
### After you have done some part of the work, you can check what has been done and what is left.

---
**Welcome route - max 50 points**

- [x] The welcome page should contain general information about the developers, project, and course **10 points**
- [x] In the upper right corner there are 2 buttons: Sign In and Sign Up **10 points**
- [x] If the login token is valid and unexpired, the Sign In and Sign Up buttons are replaced with the "Main Page" button **10 points**
- [x]  When the token expires - the user should be redirected to the "Welcome page" automatically **10 points**
- [x] Pressing the Sign In / Sign up button redirects a user to the route with the Sign In / Sign up form **10 points**

---
**Sign In / Sign Up - max 50 points**
- [x]  Buttons for Sign In / Sign Up / Sign Out are everywhere where they should be **10 points**
- [x]  Client-side validation is implemented **20 points**
- [x]  Upon successful login, the user is redirected to the Main page **10 points**
- [x]  If the user is already logged in and tries to reach these routes, they should be redirected to the Main page **10 points**

---
**GraphiQL route - max 200 points**
- [x]  Functional editor enabling query editing and prettifying **60 points**
- [x]  Operational documentation explorer, visible only upon successful SDL request **50 points**
- [x]  Variables section that can shown or hidden, specified variables are sent to the server **30 points**
- [x]  Header section that can be shown or hidden, user-added headers are sent to the server **20 points**
- [x]  Response section with an editor in read-only as a JSON viewer **40 points**

---
**General requirements - max 50 points**
- [x]  Localization **30 points**
- [x]  Sticky header **10 points**
- [x]  Errors from API side are displayed in the user friendly format **10 points**
