### ISSUE TITLE
[ Checklist ]: Penalties?

### ISSUE THREAD

**Issue by Exzorcist** [Exzorcist/graphiql-app#45]
# This task is needed to self-check our work. 
### After you have done some part of the work, you can check what has been done and what is left.

---
- [ ] React default favicon -50 points
- [x] The presence of errors and warnings in the console -20 points for each
- [ ] The presence in the console of the results of the console.log execution -20 points for each
- [ ] @ts-ignore or any usage (search through GitHub repo) -20 points for each
- [ ] The presence of code-smells (God-object, chunks of duplicate code), commented code sections: -10 points per each
- [ ] Making commits after the deadline -100 points
- [ ] Absence of tests -250 points
- [ ] Test coverage below 80% -100 points
- [ ] Absence of linting -150 points
- [ ] Absence of prettier -100 points
- [ ] Absence of husky git hooks -100 points
- [ ] Usage 3rd party / open source libraries for prettifying, i18n -150 points
- [ ] Pull Request doesn't follow guideline (including checkboxes in Score) [PR example](https://docs.rs.school/#/en/pull-request-review-process?id=pull-request-description-must-contain-the-following): -10 points
- [ ] The administration reserves the right to apply penalties for the use of incorrect repository or branch names
